# Generated by Django 4.1.5 on 2023-02-13 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpreferences', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpreference',
            options={'verbose_name_plural': 'UserPreferences'},
        ),
    ]
